### PR TITLE
Fix User Profile URL routes

### LINKED ISSUE #351: Error when url to user ends with a slash
Accessing https://twtxt.net/user/darch/ gives an error:

Screenshot 2021-01-23 at 11 28 19

But if you remove the slash `/` at the end of the url it works fine:
Screenshot 2021-01-23 at 11 28 27

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

Fixes routes for User Profiles taht were missing a trailing `/` since a
User Profile is really an "index" with a bunch of sub-routes (_think
pages_).

With `RedirectTrailingSlash` set to `true` (_the default for the custom
router used_) this correctly redirects `/user/foo` to /user/foo/` and
correctly handles `/user/foo/`.

##### Component Name

- area/backend

##### Test Plan

Tested locally

##### Additional Information

Fixes #351

### CODE REVIEW

File: internal/rice-box.go [hunk 1]
```diff
@@ -0,0 +1,580 @@
...
...ity numbers, without their express authorization and permission. In addition, you may not post intimate photos or videos that were taken or distributed without the subject’s consent.\n- **Illegal activities**: You may not use our service for any unlawful purposes or in furtherance of illegal activities. International users agree to comply with all local laws regarding online conduct and acceptable content.\n\n## What Happens If Someone Violates These Guidelines\n\nWe recognize that the circumstances under which a violation has occurred will vary, and we will tailor our response to the situation that has been reported. We’ll review each abuse report on a case-by-case basis. In each case. The actions that we will take include, but are not limited to, the following:\n\n- A warning to discontinue behavior that violates the guidelines, with specific details on how the guidelines have been violated. Repeated warnings will lead to the removal of the offending User's account and any Feeds they own.\n- Twt.social account will be closed.\n\nThanks for helping us build and maintain a safe and welcoming community on Twt.social.\n\nWe reserve the right to update these guidelines as needed.\n"),
```
Comment (aaadonai) [inline internal/rice-box.go:23]: typo on the word policy with an extra p

**Review by aaadonai — DISMISSED** [review]

File: internal/rice-box.go (hunk 1 above)
Comment (prologic) [reply internal/rice-box.go:23]: Oh gawd! 🤣 I'll fix that separately 👍

Comment (prologic) [reply internal/rice-box.go:23]: Fixed!
